import backgroundImageLight from '../assets/img/bg/BG_AMX-min.png';
import backgroundImageDark from '../assets/img/homePageBG1.png';
import AMXDark from '../assets/img/app/logoDark.svg';
import AMXBg from '../assets/img/bg/bg_sr.svg';
// import NewAMXLogo from '../assets/img/app/Alphametricx-logo-mark-dark.png';
import NewAMXLogo from '../assets/img/app/Alphametricx-logo.png';

export const theme = {
  light: {
    primary: '#675ef2',
    background: '#FFFFFF',
    text: '#656B8A',
    secondaryText: '#161A34',
    darkText: '#161A34',
    secondaryBackground: '#F6F7FB',
    backgroundImage: backgroundImageLight,
    logo: NewAMXLogo || AMXDark,
    logoText: '#ffffff',
    settingsButtonBackground: '#ffffff',
    backgroundColor: AMXBg,
    tabInactive: '#161A34',
    activeStatusBtnBg: 'rgba(97, 212, 166, 0.2)',
    inActiveStatusBtnBg: ' rgba(255, 37, 37, 0.10)',
    activeStatusBtnText: '#00CE75',
    inActiveStatusBtnText: '#FF2525',
    borders: '#c3c7d9',
    tableHeaderColor: '#5c5e60',
    closeButton: '#585858',
    errorPageText: '#585858',
    shadow: '#e8e8e8',
    newsLetterBackground: '#eceff3',
    newsLetterButtonBorder: '#535770',
    disabledBtnBackground: '#e8e8e8',
    primaryBorderRadius: '10px',
    secondaryBorderRadius: '20px',
    graphAxisColor: '#585858',
    volumeGraphTitleColor: '#F54A80',
    isIncreasedColor: '#00B929',
    isDecreasedColor: '#FF2525',
    disabledBtnColor: '#999999',
    tagsBorderColor: '#cf326b',
    keyValueColor: '#000000',
    addItemContainerColor: '#d9d9d9',
    addContentContainerThumbColor: '#a1a1a1',
    black3: '#030303',
    errorButtonBackground: '#5F39F8',
    customBrandBckgrnd: '#F4516C0D',
    customIndustryBckgrnd: '#6257E70D',
    customPeopleBckgrnd: '#08B08F0D',
    customBrandLabelColor: '#E93452',
    customIndustryLabelColor: '#4336E3',
    customPeopleLabelColor: '#049F81',
    newsletterContentBackGround: ' #f4f5f8',
    greyColor: '#d1d5dc',
    inActiverticalDots: '#5C5E60',
  },
  dark: {
    primary: '#2E68FF',
    background: '#000000',
    text: '#FFFFFF',
    secondaryText: '#000000',
    secondaryBackground: '#FFFFFF',
    backgroundImage: backgroundImageDark,
    logo: NewAMXLogo || AMXDark,
    logoText: '#ffffff',
  },
  fontFamily: 'Inter',
  responsive: {
    mobile: '768px',
    tab: '998px',
  },
};
